### ISSUE TITLE
Default mode for folder under windows

### ISSUE THREAD

**Issue by Ivan-Baranov** [sindresorhus/gulp-zip#67] opened 2016-03-04 13:11 UTC
Please add option to set default mode for folders in zip archive under windows.

**Comment by sindresorhus** [comment] 2016-03-04 15:25
Duplicate of https://github.com/sindresorhus/gulp-zip/pull/66. Please stop bothering me about it. This should be fixed in `vinyl-fs`.

**Closed by sindresorhus** 2016-03-04 15:25 UTC
